### ISSUE TITLE
Can’t run Felt with SyntaxError

### ISSUE THREAD

**Issue by youthkee** [cognitom/felt#8]
自分の環境だけかもしれませんが、うまく動かなかったので・・。
凡ミスだったらすみません。。

I’ve tried to use Felt with just described commands as below.

```
$ npm install -g felt felt-recipe-minimal
$ cd path/to/project/
$ felt
```

But I couldn’t run Felt with these error messages. 

```
/Users/youthkee/.nodebrew/node/v4.2.6/lib/node_modules/felt/lib/config-builder.js:20
module.exports = function(...configs) {
                          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/youthkee/.nodebrew/node/v4.2.6/lib/node_modules/felt/bin/index.js:12:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Is there any requirements or settings to use Felt?
My environments are here.

Mac OS X 10.10.5
node v4.2.6 (installed with nodebrew)

**Comment by cognitom** [comment]
@youthkee あ! たしかに、Node v4だと動かないですね。Node v6以上の必要があります。ご指摘感謝です。

どこかに、利用環境を追記したいと思います。

**Comment by youthkee** [comment]
ご返信ありがとうございます！
node v6.3.1で実行したところ、動作に問題ないようでしたので、こちらで色々と試してみたいと思います。

**Comment by cognitom** [comment]
ひとまずREADMEに書き足しました。 8d4aa6b3e6f9c2d5c68f8efc82e812e5b49bca46
CLIでNodeのバージョンの警告を出せるかも検討してみたいと思います。
